### ISSUE TITLE
error on Example0

### ISSUE THREAD

**Issue by leilakhalili87** [ichesser/GB_octonion_code#5] opened 2021-01-21 23:55 UTC
Hello,
I want to use this package for my research. I statrted with the tutorials. However, I am getting an error in running "Example0_conversion_to_octonion.m". Could you please help me with that?
The error is:
```
_Unable to perform assignment because the left and right sides have a different number of elements.

Error in om2ax (line 47)
                q(1) = s*abs(q(1));

Error in om2qu (line 60)
oax = om2ax(om);

Error in GBmat2oct (line 14)
pA = om2qu(OA); nA = OA(:,3)';

Error in Example0_conversion_to_octonion (line 90)
    oct = GBmat2oct(OA,OB);_
```

**Comment by ichesser** [comment] 2021-01-22 01:58
Hi, 

The issue should be resolved by adding these two lines before the function call on line 90. 
`global epsijk`
`epsijk = 1`
I pushed the relevant changes to the tutorial code. The issue is that a global variable has to be set to either +1/-1 for internal consistency of rotation representations. This is discussed in detail in this paper: https://iopscience.iop.org/article/10.1088/0965-0393/23/8/083501

Hope that helps, and please feel free to reach out with any other difficulties, 
Ian

**Comment by leilakhalili87** [comment] 2021-01-22 14:56
Thanks Ian. It worked :)

**Closed as completed** 2021-01-22 14:57 UTC
